// GENERATED FILE — do not edit by hand.
// Run `node scripts/generate-countries.mjs` to regenerate.
//
// Country names are baked in rather than derived from Intl at render time,
// because Node and browser ICU data can differ and cause a hydration mismatch.

import type { Lang } from "./languages";

export interface CountryOption {
  value: string;
  label: string;
}

export const COUNTRIES_BY_LANG: Record<Lang, CountryOption[]> = {
  de: [
    { value: "AF", label: "Afghanistan" },
    { value: "EG", label: "Ägypten" },
    { value: "AL", label: "Albanien" },
    { value: "DZ", label: "Algerien" },
    { value: "AD", label: "Andorra" },
    { value: "AO", label: "Angola" },
    { value: "AR", label: "Argentinien" },
    { value: "AM", label: "Armenien" },
    { value: "AZ", label: "Aserbaidschan" },
    { value: "ET", label: "Äthiopien" },
    { value: "AU", label: "Australien" },
    { value: "BH", label: "Bahrain" },
    { value: "BD", label: "Bangladesch" },
    { value: "BY", label: "Belarus" },
    { value: "BE", label: "Belgien" },
    { value: "BJ", label: "Benin" },
    { value: "BA", label: "Bosnien und Herzegowina" },
    { value: "BR", label: "Brasilien" },
    { value: "BG", label: "Bulgarien" },
    { value: "BF", label: "Burkina Faso" },
    { value: "BI", label: "Burundi" },
    { value: "CL", label: "Chile" },
    { value: "CN", label: "China" },
    { value: "CR", label: "Costa Rica" },
    { value: "CI", label: "Côte d’Ivoire" },
    { value: "DK", label: "Dänemark" },
    { value: "DE", label: "Deutschland" },
    { value: "DO", label: "Dominikanische Republik" },
    { value: "DJ", label: "Dschibuti" },
    { value: "EC", label: "Ecuador" },
    { value: "SV", label: "El Salvador" },
    { value: "ER", label: "Eritrea" },
    { value: "EE", label: "Estland" },
    { value: "FI", label: "Finnland" },
    { value: "FR", label: "Frankreich" },
    { value: "GA", label: "Gabun" },
    { value: "GM", label: "Gambia" },
    { value: "GE", label: "Georgien" },
    { value: "GH", label: "Ghana" },
    { value: "GR", label: "Griechenland" },
    { value: "GT", label: "Guatemala" },
    { value: "GN", label: "Guinea" },
    { value: "GW", label: "Guinea-Bissau" },
    { value: "HT", label: "Haiti" },
    { value: "HN", label: "Honduras" },
    { value: "IN", label: "Indien" },
    { value: "ID", label: "Indonesien" },
    { value: "IQ", label: "Irak" },
    { value: "IR", label: "Iran" },
    { value: "IE", label: "Irland" },
    { value: "IS", label: "Island" },
    { value: "IL", label: "Israel" },
    { value: "IT", label: "Italien" },
    { value: "JM", label: "Jamaika" },
    { value: "JP", label: "Japan" },
    { value: "YE", label: "Jemen" },
    { value: "JO", label: "Jordanien" },
    { value: "KH", label: "Kambodscha" },
    { value: "CM", label: "Kamerun" },
    { value: "CA", label: "Kanada" },
    { value: "KZ", label: "Kasachstan" },
    { value: "QA", label: "Katar" },
    { value: "KE", label: "Kenia" },
    { value: "KG", label: "Kirgisistan" },
    { value: "CO", label: "Kolumbien" },
    { value: "KM", label: "Komoren" },
    { value: "CG", label: "Kongo-Brazzaville" },
    { value: "CD", label: "Kongo-Kinshasa" },
    { value: "HR", label: "Kroatien" },
    { value: "CU", label: "Kuba" },
    { value: "KW", label: "Kuwait" },
    { value: "LA", label: "Laos" },
    { value: "LV", label: "Lettland" },
    { value: "LB", label: "Libanon" },
    { value: "LY", label: "Libyen" },
    { value: "LT", label: "Litauen" },
    { value: "LU", label: "Luxemburg" },
    { value: "MG", label: "Madagaskar" },
    { value: "MW", label: "Malawi" },
    { value: "MY", label: "Malaysia" },
    { value: "ML", label: "Mali" },
    { value: "MT", label: "Malta" },
    { value: "MA", label: "Marokko" },
    { value: "MR", label: "Mauretanien" },
    { value: "MU", label: "Mauritius" },
    { value: "MX", label: "Mexiko" },
    { value: "MN", label: "Mongolei" },
    { value: "ME", label: "Montenegro" },
    { value: "MZ", label: "Mosambik" },
    { value: "MM", label: "Myanmar" },
    { value: "NA", label: "Namibia" },
    { value: "NP", label: "Nepal" },
    { value: "NZ", label: "Neuseeland" },
    { value: "NI", label: "Nicaragua" },
    { value: "NL", label: "Niederlande" },
    { value: "NE", label: "Niger" },
    { value: "NG", label: "Nigeria" },
    { value: "MK", label: "Nordmazedonien" },
    { value: "NO", label: "Norwegen" },
    { value: "OM", label: "Oman" },
    { value: "AT", label: "Österreich" },
    { value: "PK", label: "Pakistan" },
    { value: "PS", label: "Palästinensische Autonomiegebiete" },
    { value: "PA", label: "Panama" },
    { value: "PY", label: "Paraguay" },
    { value: "PE", label: "Peru" },
    { value: "PH", label: "Philippinen" },
    { value: "PL", label: "Polen" },
    { value: "PT", label: "Portugal" },
    { value: "MD", label: "Republik Moldau" },
    { value: "RW", label: "Ruanda" },
    { value: "RO", label: "Rumänien" },
    { value: "RU", label: "Russland" },
    { value: "ZM", label: "Sambia" },
    { value: "SA", label: "Saudi-Arabien" },
    { value: "SE", label: "Schweden" },
    { value: "CH", label: "Schweiz" },
    { value: "SN", label: "Senegal" },
    { value: "RS", label: "Serbien" },
    { value: "SL", label: "Sierra Leone" },
    { value: "ZW", label: "Simbabwe" },
    { value: "SG", label: "Singapur" },
    { value: "SK", label: "Slowakei" },
    { value: "SI", label: "Slowenien" },
    { value: "SO", label: "Somalia" },
    { value: "ES", label: "Spanien" },
    { value: "LK", label: "Sri Lanka" },
    { value: "ZA", label: "Südafrika" },
    { value: "SD", label: "Sudan" },
    { value: "KR", label: "Südkorea" },
    { value: "SS", label: "Südsudan" },
    { value: "SY", label: "Syrien" },
    { value: "TJ", label: "Tadschikistan" },
    { value: "TW", label: "Taiwan" },
    { value: "TZ", label: "Tansania" },
    { value: "TH", label: "Thailand" },
    { value: "TG", label: "Togo" },
    { value: "TD", label: "Tschad" },
    { value: "CZ", label: "Tschechien" },
    { value: "TN", label: "Tunesien" },
    { value: "TR", label: "Türkei" },
    { value: "TM", label: "Turkmenistan" },
    { value: "UG", label: "Uganda" },
    { value: "UA", label: "Ukraine" },
    { value: "HU", label: "Ungarn" },
    { value: "UY", label: "Uruguay" },
    { value: "UZ", label: "Usbekistan" },
    { value: "VE", label: "Venezuela" },
    { value: "AE", label: "Vereinigte Arabische Emirate" },
    { value: "US", label: "Vereinigte Staaten" },
    { value: "GB", label: "Vereinigtes Königreich" },
    { value: "VN", label: "Vietnam" },
    { value: "CY", label: "Zypern" },
  ],
  en: [
    { value: "AF", label: "Afghanistan" },
    { value: "AL", label: "Albania" },
    { value: "DZ", label: "Algeria" },
    { value: "AD", label: "Andorra" },
    { value: "AO", label: "Angola" },
    { value: "AR", label: "Argentina" },
    { value: "AM", label: "Armenia" },
    { value: "AU", label: "Australia" },
    { value: "AT", label: "Austria" },
    { value: "AZ", label: "Azerbaijan" },
    { value: "BH", label: "Bahrain" },
    { value: "BD", label: "Bangladesh" },
    { value: "BY", label: "Belarus" },
    { value: "BE", label: "Belgium" },
    { value: "BJ", label: "Benin" },
    { value: "BA", label: "Bosnia & Herzegovina" },
    { value: "BR", label: "Brazil" },
    { value: "BG", label: "Bulgaria" },
    { value: "BF", label: "Burkina Faso" },
    { value: "BI", label: "Burundi" },
    { value: "KH", label: "Cambodia" },
    { value: "CM", label: "Cameroon" },
    { value: "CA", label: "Canada" },
    { value: "TD", label: "Chad" },
    { value: "CL", label: "Chile" },
    { value: "CN", label: "China" },
    { value: "CO", label: "Colombia" },
    { value: "KM", label: "Comoros" },
    { value: "CG", label: "Congo - Brazzaville" },
    { value: "CD", label: "Congo - Kinshasa" },
    { value: "CR", label: "Costa Rica" },
    { value: "CI", label: "Côte d’Ivoire" },
    { value: "HR", label: "Croatia" },
    { value: "CU", label: "Cuba" },
    { value: "CY", label: "Cyprus" },
    { value: "CZ", label: "Czechia" },
    { value: "DK", label: "Denmark" },
    { value: "DJ", label: "Djibouti" },
    { value: "DO", label: "Dominican Republic" },
    { value: "EC", label: "Ecuador" },
    { value: "EG", label: "Egypt" },
    { value: "SV", label: "El Salvador" },
    { value: "ER", label: "Eritrea" },
    { value: "EE", label: "Estonia" },
    { value: "ET", label: "Ethiopia" },
    { value: "FI", label: "Finland" },
    { value: "FR", label: "France" },
    { value: "GA", label: "Gabon" },
    { value: "GM", label: "Gambia" },
    { value: "GE", label: "Georgia" },
    { value: "DE", label: "Germany" },
    { value: "GH", label: "Ghana" },
    { value: "GR", label: "Greece" },
    { value: "GT", label: "Guatemala" },
    { value: "GN", label: "Guinea" },
    { value: "GW", label: "Guinea-Bissau" },
    { value: "HT", label: "Haiti" },
    { value: "HN", label: "Honduras" },
    { value: "HU", label: "Hungary" },
    { value: "IS", label: "Iceland" },
    { value: "IN", label: "India" },
    { value: "ID", label: "Indonesia" },
    { value: "IR", label: "Iran" },
    { value: "IQ", label: "Iraq" },
    { value: "IE", label: "Ireland" },
    { value: "IL", label: "Israel" },
    { value: "IT", label: "Italy" },
    { value: "JM", label: "Jamaica" },
    { value: "JP", label: "Japan" },
    { value: "JO", label: "Jordan" },
    { value: "KZ", label: "Kazakhstan" },
    { value: "KE", label: "Kenya" },
    { value: "KW", label: "Kuwait" },
    { value: "KG", label: "Kyrgyzstan" },
    { value: "LA", label: "Laos" },
    { value: "LV", label: "Latvia" },
    { value: "LB", label: "Lebanon" },
    { value: "LY", label: "Libya" },
    { value: "LT", label: "Lithuania" },
    { value: "LU", label: "Luxembourg" },
    { value: "MG", label: "Madagascar" },
    { value: "MW", label: "Malawi" },
    { value: "MY", label: "Malaysia" },
    { value: "ML", label: "Mali" },
    { value: "MT", label: "Malta" },
    { value: "MR", label: "Mauritania" },
    { value: "MU", label: "Mauritius" },
    { value: "MX", label: "Mexico" },
    { value: "MD", label: "Moldova" },
    { value: "MN", label: "Mongolia" },
    { value: "ME", label: "Montenegro" },
    { value: "MA", label: "Morocco" },
    { value: "MZ", label: "Mozambique" },
    { value: "MM", label: "Myanmar (Burma)" },
    { value: "NA", label: "Namibia" },
    { value: "NP", label: "Nepal" },
    { value: "NL", label: "Netherlands" },
    { value: "NZ", label: "New Zealand" },
    { value: "NI", label: "Nicaragua" },
    { value: "NE", label: "Niger" },
    { value: "NG", label: "Nigeria" },
    { value: "MK", label: "North Macedonia" },
    { value: "NO", label: "Norway" },
    { value: "OM", label: "Oman" },
    { value: "PK", label: "Pakistan" },
    { value: "PS", label: "Palestinian Territories" },
    { value: "PA", label: "Panama" },
    { value: "PY", label: "Paraguay" },
    { value: "PE", label: "Peru" },
    { value: "PH", label: "Philippines" },
    { value: "PL", label: "Poland" },
    { value: "PT", label: "Portugal" },
    { value: "QA", label: "Qatar" },
    { value: "RO", label: "Romania" },
    { value: "RU", label: "Russia" },
    { value: "RW", label: "Rwanda" },
    { value: "SA", label: "Saudi Arabia" },
    { value: "SN", label: "Senegal" },
    { value: "RS", label: "Serbia" },
    { value: "SL", label: "Sierra Leone" },
    { value: "SG", label: "Singapore" },
    { value: "SK", label: "Slovakia" },
    { value: "SI", label: "Slovenia" },
    { value: "SO", label: "Somalia" },
    { value: "ZA", label: "South Africa" },
    { value: "KR", label: "South Korea" },
    { value: "SS", label: "South Sudan" },
    { value: "ES", label: "Spain" },
    { value: "LK", label: "Sri Lanka" },
    { value: "SD", label: "Sudan" },
    { value: "SE", label: "Sweden" },
    { value: "CH", label: "Switzerland" },
    { value: "SY", label: "Syria" },
    { value: "TW", label: "Taiwan" },
    { value: "TJ", label: "Tajikistan" },
    { value: "TZ", label: "Tanzania" },
    { value: "TH", label: "Thailand" },
    { value: "TG", label: "Togo" },
    { value: "TN", label: "Tunisia" },
    { value: "TR", label: "Türkiye" },
    { value: "TM", label: "Turkmenistan" },
    { value: "UG", label: "Uganda" },
    { value: "UA", label: "Ukraine" },
    { value: "AE", label: "United Arab Emirates" },
    { value: "GB", label: "United Kingdom" },
    { value: "US", label: "United States" },
    { value: "UY", label: "Uruguay" },
    { value: "UZ", label: "Uzbekistan" },
    { value: "VE", label: "Venezuela" },
    { value: "VN", label: "Vietnam" },
    { value: "YE", label: "Yemen" },
    { value: "ZM", label: "Zambia" },
    { value: "ZW", label: "Zimbabwe" },
  ],
  ar: [
    { value: "IS", label: "آيسلندا" },
    { value: "ET", label: "إثيوبيا" },
    { value: "AZ", label: "أذربيجان" },
    { value: "AM", label: "أرمينيا" },
    { value: "ER", label: "إريتريا" },
    { value: "ES", label: "إسبانيا" },
    { value: "AU", label: "أستراليا" },
    { value: "EE", label: "إستونيا" },
    { value: "IL", label: "إسرائيل" },
    { value: "AF", label: "أفغانستان" },
    { value: "PS", label: "الأراضي الفلسطينية" },
    { value: "AR", label: "الأرجنتين" },
    { value: "JO", label: "الأردن" },
    { value: "EC", label: "الإكوادور" },
    { value: "AE", label: "الإمارات العربية المتحدة" },
    { value: "AL", label: "ألبانيا" },
    { value: "BH", label: "البحرين" },
    { value: "BR", label: "البرازيل" },
    { value: "PT", label: "البرتغال" },
    { value: "BA", label: "البوسنة والهرسك" },
    { value: "CZ", label: "التشيك" },
    { value: "ME", label: "الجبل الأسود" },
    { value: "DZ", label: "الجزائر" },
    { value: "DK", label: "الدانمرك" },
    { value: "SV", label: "السلفادور" },
    { value: "SN", label: "السنغال" },
    { value: "SD", label: "السودان" },
    { value: "SE", label: "السويد" },
    { value: "SO", label: "الصومال" },
    { value: "CN", label: "الصين" },
    { value: "IQ", label: "العراق" },
    { value: "GA", label: "الغابون" },
    { value: "PH", label: "الفلبين" },
    { value: "CM", label: "الكاميرون" },
    { value: "CG", label: "الكونغو - برازافيل" },
    { value: "CD", label: "الكونغو - كينشاسا" },
    { value: "KW", label: "الكويت" },
    { value: "DE", label: "ألمانيا" },
    { value: "MA", label: "المغرب" },
    { value: "MX", label: "المكسيك" },
    { value: "SA", label: "المملكة العربية السعودية" },
    { value: "GB", label: "المملكة المتحدة" },
    { value: "NO", label: "النرويج" },
    { value: "AT", label: "النمسا" },
    { value: "NE", label: "النيجر" },
    { value: "IN", label: "الهند" },
    { value: "US", label: "الولايات المتحدة" },
    { value: "JP", label: "اليابان" },
    { value: "YE", label: "اليمن" },
    { value: "GR", label: "اليونان" },
    { value: "AD", label: "أندورا" },
    { value: "ID", label: "إندونيسيا" },
    { value: "AO", label: "أنغولا" },
    { value: "UY", label: "أورغواي" },
    { value: "UZ", label: "أوزبكستان" },
    { value: "UG", label: "أوغندا" },
    { value: "UA", label: "أوكرانيا" },
    { value: "IR", label: "إيران" },
    { value: "IE", label: "أيرلندا" },
    { value: "IT", label: "إيطاليا" },
    { value: "PY", label: "باراغواي" },
    { value: "PK", label: "باكستان" },
    { value: "BE", label: "بلجيكا" },
    { value: "BG", label: "بلغاريا" },
    { value: "BD", label: "بنغلاديش" },
    { value: "PA", label: "بنما" },
    { value: "BJ", label: "بنين" },
    { value: "BF", label: "بوركينا فاسو" },
    { value: "BI", label: "بوروندي" },
    { value: "PL", label: "بولندا" },
    { value: "PE", label: "بيرو" },
    { value: "BY", label: "بيلاروس" },
    { value: "TH", label: "تايلاند" },
    { value: "TW", label: "تايوان" },
    { value: "TM", label: "تركمانستان" },
    { value: "TR", label: "تركيا" },
    { value: "TD", label: "تشاد" },
    { value: "CL", label: "تشيلي" },
    { value: "TZ", label: "تنزانيا" },
    { value: "TG", label: "توغو" },
    { value: "TN", label: "تونس" },
    { value: "JM", label: "جامايكا" },
    { value: "KM", label: "جزر القمر" },
    { value: "DO", label: "جمهورية الدومينيكان" },
    { value: "ZA", label: "جنوب أفريقيا" },
    { value: "SS", label: "جنوب السودان" },
    { value: "GE", label: "جورجيا" },
    { value: "DJ", label: "جيبوتي" },
    { value: "RW", label: "رواندا" },
    { value: "RU", label: "روسيا" },
    { value: "RO", label: "رومانيا" },
    { value: "ZM", label: "زامبيا" },
    { value: "ZW", label: "زيمبابوي" },
    { value: "CI", label: "ساحل العاج" },
    { value: "LK", label: "سريلانكا" },
    { value: "SK", label: "سلوفاكيا" },
    { value: "SI", label: "سلوفينيا" },
    { value: "SG", label: "سنغافورة" },
    { value: "SY", label: "سوريا" },
    { value: "CH", label: "سويسرا" },
    { value: "SL", label: "سيراليون" },
    { value: "RS", label: "صربيا" },
    { value: "TJ", label: "طاجيكستان" },
    { value: "OM", label: "عُمان" },
    { value: "GM", label: "غامبيا" },
    { value: "GH", label: "غانا" },
    { value: "GT", label: "غواتيمالا" },
    { value: "GN", label: "غينيا" },
    { value: "GW", label: "غينيا بيساو" },
    { value: "FR", label: "فرنسا" },
    { value: "VE", label: "فنزويلا" },
    { value: "FI", label: "فنلندا" },
    { value: "VN", label: "فيتنام" },
    { value: "CY", label: "قبرص" },
    { value: "QA", label: "قطر" },
    { value: "KG", label: "قيرغيزستان" },
    { value: "KZ", label: "كازاخستان" },
    { value: "HR", label: "كرواتيا" },
    { value: "KH", label: "كمبوديا" },
    { value: "CA", label: "كندا" },
    { value: "CU", label: "كوبا" },
    { value: "KR", label: "كوريا الجنوبية" },
    { value: "CR", label: "كوستاريكا" },
    { value: "CO", label: "كولومبيا" },
    { value: "KE", label: "كينيا" },
    { value: "LV", label: "لاتفيا" },
    { value: "LA", label: "لاوس" },
    { value: "LB", label: "لبنان" },
    { value: "LU", label: "لوكسمبورغ" },
    { value: "LY", label: "ليبيا" },
    { value: "LT", label: "ليتوانيا" },
    { value: "MT", label: "مالطا" },
    { value: "ML", label: "مالي" },
    { value: "MY", label: "ماليزيا" },
    { value: "MG", label: "مدغشقر" },
    { value: "EG", label: "مصر" },
    { value: "MK", label: "مقدونيا الشمالية" },
    { value: "MW", label: "ملاوي" },
    { value: "MN", label: "منغوليا" },
    { value: "MR", label: "موريتانيا" },
    { value: "MU", label: "موريشيوس" },
    { value: "MZ", label: "موزمبيق" },
    { value: "MD", label: "مولدوفا" },
    { value: "MM", label: "ميانمار (بورما)" },
    { value: "NA", label: "ناميبيا" },
    { value: "NP", label: "نيبال" },
    { value: "NG", label: "نيجيريا" },
    { value: "NI", label: "نيكاراغوا" },
    { value: "NZ", label: "نيوزيلندا" },
    { value: "HT", label: "هايتي" },
    { value: "HN", label: "هندوراس" },
    { value: "HU", label: "هنغاريا" },
    { value: "NL", label: "هولندا" },
  ],
  fr: [
    { value: "AF", label: "Afghanistan" },
    { value: "ZA", label: "Afrique du Sud" },
    { value: "AL", label: "Albanie" },
    { value: "DZ", label: "Algérie" },
    { value: "DE", label: "Allemagne" },
    { value: "AD", label: "Andorre" },
    { value: "AO", label: "Angola" },
    { value: "SA", label: "Arabie saoudite" },
    { value: "AR", label: "Argentine" },
    { value: "AM", label: "Arménie" },
    { value: "AU", label: "Australie" },
    { value: "AT", label: "Autriche" },
    { value: "AZ", label: "Azerbaïdjan" },
    { value: "BH", label: "Bahreïn" },
    { value: "BD", label: "Bangladesh" },
    { value: "BE", label: "Belgique" },
    { value: "BJ", label: "Bénin" },
    { value: "BY", label: "Biélorussie" },
    { value: "BA", label: "Bosnie-Herzégovine" },
    { value: "BR", label: "Brésil" },
    { value: "BG", label: "Bulgarie" },
    { value: "BF", label: "Burkina Faso" },
    { value: "BI", label: "Burundi" },
    { value: "KH", label: "Cambodge" },
    { value: "CM", label: "Cameroun" },
    { value: "CA", label: "Canada" },
    { value: "CL", label: "Chili" },
    { value: "CN", label: "Chine" },
    { value: "CY", label: "Chypre" },
    { value: "CO", label: "Colombie" },
    { value: "KM", label: "Comores" },
    { value: "CG", label: "Congo-Brazzaville" },
    { value: "CD", label: "Congo-Kinshasa" },
    { value: "KR", label: "Corée du Sud" },
    { value: "CR", label: "Costa Rica" },
    { value: "CI", label: "Côte d’Ivoire" },
    { value: "HR", label: "Croatie" },
    { value: "CU", label: "Cuba" },
    { value: "DK", label: "Danemark" },
    { value: "DJ", label: "Djibouti" },
    { value: "EG", label: "Égypte" },
    { value: "AE", label: "Émirats arabes unis" },
    { value: "EC", label: "Équateur" },
    { value: "ER", label: "Érythrée" },
    { value: "ES", label: "Espagne" },
    { value: "EE", label: "Estonie" },
    { value: "US", label: "États-Unis" },
    { value: "ET", label: "Éthiopie" },
    { value: "FI", label: "Finlande" },
    { value: "FR", label: "France" },
    { value: "GA", label: "Gabon" },
    { value: "GM", label: "Gambie" },
    { value: "GE", label: "Géorgie" },
    { value: "GH", label: "Ghana" },
    { value: "GR", label: "Grèce" },
    { value: "GT", label: "Guatemala" },
    { value: "GN", label: "Guinée" },
    { value: "GW", label: "Guinée-Bissau" },
    { value: "HT", label: "Haïti" },
    { value: "HN", label: "Honduras" },
    { value: "HU", label: "Hongrie" },
    { value: "IN", label: "Inde" },
    { value: "ID", label: "Indonésie" },
    { value: "IQ", label: "Irak" },
    { value: "IR", label: "Iran" },
    { value: "IE", label: "Irlande" },
    { value: "IS", label: "Islande" },
    { value: "IL", label: "Israël" },
    { value: "IT", label: "Italie" },
    { value: "JM", label: "Jamaïque" },
    { value: "JP", label: "Japon" },
    { value: "JO", label: "Jordanie" },
    { value: "KZ", label: "Kazakhstan" },
    { value: "KE", label: "Kenya" },
    { value: "KG", label: "Kirghizstan" },
    { value: "KW", label: "Koweït" },
    { value: "LA", label: "Laos" },
    { value: "LV", label: "Lettonie" },
    { value: "LB", label: "Liban" },
    { value: "LY", label: "Libye" },
    { value: "LT", label: "Lituanie" },
    { value: "LU", label: "Luxembourg" },
    { value: "MK", label: "Macédoine du Nord" },
    { value: "MG", label: "Madagascar" },
    { value: "MY", label: "Malaisie" },
    { value: "MW", label: "Malawi" },
    { value: "ML", label: "Mali" },
    { value: "MT", label: "Malte" },
    { value: "MA", label: "Maroc" },
    { value: "MU", label: "Maurice" },
    { value: "MR", label: "Mauritanie" },
    { value: "MX", label: "Mexique" },
    { value: "MD", label: "Moldavie" },
    { value: "MN", label: "Mongolie" },
    { value: "ME", label: "Monténégro" },
    { value: "MZ", label: "Mozambique" },
    { value: "MM", label: "Myanmar (Birmanie)" },
    { value: "NA", label: "Namibie" },
    { value: "NP", label: "Népal" },
    { value: "NI", label: "Nicaragua" },
    { value: "NE", label: "Niger" },
    { value: "NG", label: "Nigeria" },
    { value: "NO", label: "Norvège" },
    { value: "NZ", label: "Nouvelle-Zélande" },
    { value: "OM", label: "Oman" },
    { value: "UG", label: "Ouganda" },
    { value: "UZ", label: "Ouzbékistan" },
    { value: "PK", label: "Pakistan" },
    { value: "PA", label: "Panama" },
    { value: "PY", label: "Paraguay" },
    { value: "NL", label: "Pays-Bas" },
    { value: "PE", label: "Pérou" },
    { value: "PH", label: "Philippines" },
    { value: "PL", label: "Pologne" },
    { value: "PT", label: "Portugal" },
    { value: "QA", label: "Qatar" },
    { value: "DO", label: "République dominicaine" },
    { value: "RO", label: "Roumanie" },
    { value: "GB", label: "Royaume-Uni" },
    { value: "RU", label: "Russie" },
    { value: "RW", label: "Rwanda" },
    { value: "SV", label: "Salvador" },
    { value: "SN", label: "Sénégal" },
    { value: "RS", label: "Serbie" },
    { value: "SL", label: "Sierra Leone" },
    { value: "SG", label: "Singapour" },
    { value: "SK", label: "Slovaquie" },
    { value: "SI", label: "Slovénie" },
    { value: "SO", label: "Somalie" },
    { value: "SD", label: "Soudan" },
    { value: "SS", label: "Soudan du Sud" },
    { value: "LK", label: "Sri Lanka" },
    { value: "SE", label: "Suède" },
    { value: "CH", label: "Suisse" },
    { value: "SY", label: "Syrie" },
    { value: "TJ", label: "Tadjikistan" },
    { value: "TW", label: "Taïwan" },
    { value: "TZ", label: "Tanzanie" },
    { value: "TD", label: "Tchad" },
    { value: "CZ", label: "Tchéquie" },
    { value: "PS", label: "Territoires palestiniens" },
    { value: "TH", label: "Thaïlande" },
    { value: "TG", label: "Togo" },
    { value: "TN", label: "Tunisie" },
    { value: "TM", label: "Turkménistan" },
    { value: "TR", label: "Turquie" },
    { value: "UA", label: "Ukraine" },
    { value: "UY", label: "Uruguay" },
    { value: "VE", label: "Venezuela" },
    { value: "VN", label: "Viêt Nam" },
    { value: "YE", label: "Yémen" },
    { value: "ZM", label: "Zambie" },
    { value: "ZW", label: "Zimbabwe" },
  ],
};
